name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o probe-linux-amd64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o probe-linux-arm64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o probe-linux-arm6.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o probe-linux-arm7.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go

          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o probe-windows-amd64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o probe-windows-arm64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=6 go build -o probe-windows-arm6.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=7 go build -o probe-windows-arm7.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go

          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o probe-darwin-amd64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o probe-darwin-arm64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go

          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o probe-freebsd-amd64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm64 go build -o probe-freebsd-arm64.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=6 go build -o probe-freebsd-arm6.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go
          CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=7 go build -o probe-freebsd-arm7.exe -ldflags="-s -w -extldflags=-static" cmd/probe/main.go

      - name: Run tests
        run: |
          go test --race -v -count=1 -coverprofile=coverage.out ./...
